CREATE TABLE [dbo].[Product] (
    [ProductID]        INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [ProductName]      NVARCHAR (50)  NULL,
    [Price]            INT            NOT NULL,
    [PicURL]           NVARCHAR (MAX) NULL,
    [CatID]            INT            NOT NULL,
    [IsAvailable]      BIT            NULL,
    [Code]             NVARCHAR (50)  CONSTRAINT [DF_Product_Code] DEFAULT ('code') NOT NULL,
    [DiscountPercent]  INT            CONSTRAINT [DF_Product_DiscountPercent] DEFAULT ((0)) NOT NULL,
    [DiscountPrice]    INT            CONSTRAINT [DF_Product_DiscountPrice] DEFAULT ((0)) NOT NULL,
    [ProductType]      INT            CONSTRAINT [DF_Product_ProductType] DEFAULT ((0)) NOT NULL,
    [DisplayOrder]     INT            NOT NULL,
    [HasExtra]         BIT            NOT NULL,
    [IsFixedPrice]     BIT            CONSTRAINT [DF_Product_IsFixedPrice] DEFAULT ((0)) NOT NULL,
    [PosX]             INT            NULL,
    [PosY]             INT            NULL,
    [ColorGroup]       INT            NULL,
    [Group]            INT            NULL,
    [GroupId]          INT            NULL,
    [IsMenuDisplay]    BIT            NULL,
    [GeneralProductId] INT            NULL,
    [Att1]             NVARCHAR (50)  NULL,
    [Att2]             NVARCHAR (50)  NULL,
    [Att3]             NVARCHAR (50)  NULL,
    [MaxExtra]         INT            NULL,
    [Description]      NVARCHAR (MAX) NULL,
    [PrintGroup]       INT            NULL,
    CONSTRAINT [PK__Product__61316BF4] PRIMARY KEY CLUSTERED ([ProductID] ASC),
    CONSTRAINT [FK_Product_Group] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Group] ([GroupId]),
    CONSTRAINT [FK_Product_ProductCategory1] FOREIGN KEY ([CatID]) REFERENCES [dbo].[ProductCategory] ([CateID])
);

