//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string CommentContent { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> NumberOfLike { get; set; }
        public Nullable<int> NumberOfDislike { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
