//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interaction
    {
        public int InteractionId { get; set; }
        public Nullable<int> SessionId { get; set; }
        public string InteractionName { get; set; }
        public Nullable<int> InteractionTypeId { get; set; }
        public Nullable<int> InteractionItemId { get; set; }
        public Nullable<bool> IsRunning { get; set; }
    
        public virtual InteractionType InteractionType { get; set; }
        public virtual QA QA { get; set; }
        public virtual Session Session { get; set; }
        public virtual Voting Voting { get; set; }
    }
}
