//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int QuestionId { get; set; }
        public Nullable<int> QAId { get; set; }
        public string QuestionContent { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> NumberOfLike { get; set; }
    
        public virtual QA QA { get; set; }
    }
}
