//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ICollectionItemService : SkyWeb.DatVM.Data.IBaseService<CollectionItem>
    {
    }
    
    public partial class CollectionItemService : SkyWeb.DatVM.Data.BaseService<CollectionItem>, ICollectionItemService
    {
        public CollectionItemService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ICollectionItemRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
