//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ICommentService : SkyWeb.DatVM.Data.IBaseService<Comment>
    {
    }
    
    public partial class CommentService : SkyWeb.DatVM.Data.BaseService<Comment>, ICommentService
    {
        public CommentService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ICommentRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
