//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IInteractionTypeService : SkyWeb.DatVM.Data.IBaseService<InteractionType>
    {
    }
    
    public partial class InteractionTypeService : SkyWeb.DatVM.Data.BaseService<InteractionType>, IInteractionTypeService
    {
        public InteractionTypeService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IInteractionTypeRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
