//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IInteractionService : SkyWeb.DatVM.Data.IBaseService<Interaction>
    {
    }
    
    public partial class InteractionService : SkyWeb.DatVM.Data.BaseService<Interaction>, IInteractionService
    {
        public InteractionService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IInteractionRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
