//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IVotingOptionService : SkyWeb.DatVM.Data.IBaseService<VotingOption>
    {
    }
    
    public partial class VotingOptionService : SkyWeb.DatVM.Data.BaseService<VotingOption>, IVotingOptionService
    {
        public VotingOptionService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IVotingOptionRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
