//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IVotingQuestionService : SkyWeb.DatVM.Data.IBaseService<VotingQuestion>
    {
    }
    
    public partial class VotingQuestionService : SkyWeb.DatVM.Data.BaseService<VotingQuestion>, IVotingQuestionService
    {
        public VotingQuestionService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IVotingQuestionRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
