//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IVotingService : SkyWeb.DatVM.Data.IBaseService<Voting>
    {
    }
    
    public partial class VotingService : SkyWeb.DatVM.Data.BaseService<Voting>, IVotingService
    {
        public VotingService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IVotingRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
