//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityItemViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.ActivityItem>
    {
    	
    			public virtual int ActivityItemId { get; set; }
    			public virtual int ActivityId { get; set; }
    			public virtual int CollectionItemId { get; set; }
    	
    	public ActivityItemViewModel() : base() { }
    	public ActivityItemViewModel(HmsService.Models.Entities.ActivityItem entity) : base(entity) { }
    
    }
}
