//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.Activity>
    {
    	
    			public virtual int ActivityID { get; set; }
    			public virtual string Name { get; set; }
    			public virtual int SessionId { get; set; }
    			public virtual Nullable<System.DateTime> StartTime { get; set; }
    			public virtual Nullable<System.DateTime> EndTime { get; set; }
    			public virtual string Description { get; set; }
    	
    	public ActivityViewModel() : base() { }
    	public ActivityViewModel(HmsService.Models.Entities.Activity entity) : base(entity) { }
    
    }
}
