//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRoleViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.AspNetRole>
    {
    	
    			public virtual string Id { get; set; }
    			public virtual string Name { get; set; }
    	
    	public AspNetRoleViewModel() : base() { }
    	public AspNetRoleViewModel(HmsService.Models.Entities.AspNetRole entity) : base(entity) { }
    
    }
}
