//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionItemViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.CollectionItem>
    {
    	
    			public virtual int CollectionItemID { get; set; }
    			public virtual string Name { get; set; }
    			public virtual string Desciption { get; set; }
    			public virtual string ImageUrl { get; set; }
    			public virtual int EventCollectionId { get; set; }
    	
    	public CollectionItemViewModel() : base() { }
    	public CollectionItemViewModel(HmsService.Models.Entities.CollectionItem entity) : base(entity) { }
    
    }
}
