//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.Comment>
    {
    	
    			public virtual int CommentId { get; set; }
    			public virtual Nullable<int> QuestionId { get; set; }
    			public virtual string CommentContent { get; set; }
    			public virtual string Username { get; set; }
    			public virtual Nullable<System.DateTime> CreateTime { get; set; }
    			public virtual Nullable<int> NumberOfLike { get; set; }
    	
    	public CommentViewModel() : base() { }
    	public CommentViewModel(HmsService.Models.Entities.Comment entity) : base(entity) { }
    
    }
}
