//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCollectionViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.EventCollection>
    {
    	
    			public virtual int EventCollectionID { get; set; }
    			public virtual string Name { get; set; }
    			public virtual int EventId { get; set; }
    			public virtual int TypeId { get; set; }
    			public virtual string Description { get; set; }
    	
    	public EventCollectionViewModel() : base() { }
    	public EventCollectionViewModel(HmsService.Models.Entities.EventCollection entity) : base(entity) { }
    
    }
}
