//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.Event>
    {
    	
    			public virtual int EventID { get; set; }
    			public virtual string Name { get; set; }
    			public virtual string EventDescription { get; set; }
    			public virtual Nullable<System.DateTime> StartTime { get; set; }
    			public virtual Nullable<System.DateTime> EndTime { get; set; }
    			public virtual Nullable<System.DateTime> CreateTime { get; set; }
    			public virtual string Address { get; set; }
    			public virtual Nullable<int> TemplateId { get; set; }
    			public virtual Nullable<int> CodeLogin { get; set; }
    			public virtual string ImageURL { get; set; }
    			public virtual Nullable<bool> IsActive { get; set; }
    	
    	public EventViewModel() : base() { }
    	public EventViewModel(HmsService.Models.Entities.Event entity) : base(entity) { }
    
    }
}
