//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.Guest>
    {
    	
    			public virtual int GuestId { get; set; }
    			public virtual string GuestName { get; set; }
    			public virtual string GuestEmail { get; set; }
    			public virtual string GuestPhone { get; set; }
    			public virtual int EventId { get; set; }
    			public virtual Nullable<bool> IsCheckIn { get; set; }
    			public virtual Nullable<System.DateTime> TimeRegister { get; set; }
    	
    	public GuestViewModel() : base() { }
    	public GuestViewModel(HmsService.Models.Entities.Guest entity) : base(entity) { }
    
    }
}
