//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.Question>
    {
    	
    			public virtual int QuestionId { get; set; }
    			public virtual Nullable<int> QAId { get; set; }
    			public virtual string QuestionContent { get; set; }
    			public virtual string Username { get; set; }
    			public virtual Nullable<System.DateTime> CreateTime { get; set; }
    			public virtual Nullable<int> NumberOfLike { get; set; }
    			public virtual Nullable<bool> IsAnswer { get; set; }
    			public virtual Nullable<int> NumberOfDislike { get; set; }
    	
    	public QuestionViewModel() : base() { }
    	public QuestionViewModel(HmsService.Models.Entities.Question entity) : base(entity) { }
    
    }
}
