//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimelineViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.Timeline>
    {
    	
    			public virtual int TimelineId { get; set; }
    			public virtual int SessionId { get; set; }
    			public virtual string TimelineTitle { get; set; }
    			public virtual string TimelineDetail { get; set; }
    			public virtual Nullable<System.DateTime> StartTime { get; set; }
    	
    	public TimelineViewModel() : base() { }
    	public TimelineViewModel(HmsService.Models.Entities.Timeline entity) : base(entity) { }
    
    }
}
