//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotingQuestionViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.VotingQuestion>
    {
    	
    			public virtual int VotingQuestionId { get; set; }
    			public virtual string VotingQuestionDetail { get; set; }
    			public virtual Nullable<int> VotingId { get; set; }
    	
    	public VotingQuestionViewModel() : base() { }
    	public VotingQuestionViewModel(HmsService.Models.Entities.VotingQuestion entity) : base(entity) { }
    
    }
}
