//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HmsService.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotingOptionViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<HmsService.Models.Entities.VotingOption>
    {
    	
    			public virtual int VotingOptionId { get; set; }
    			public virtual Nullable<int> VotingQuestionId { get; set; }
    			public virtual string VotingOptionDetail { get; set; }
    			public virtual Nullable<int> NumberOfVoting { get; set; }
    	
    	public VotingOptionViewModel() : base() { }
    	public VotingOptionViewModel(HmsService.Models.Entities.VotingOption entity) : base(entity) { }
    
    }
}
